title: Photo Agency for the Design Press
purpose: []
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.125
  brandStrength: 0
  rhythmicContrast: 0.5
  brandColors:
    - '#ffffff'
    - '#ffffff'
    - '#ffffff'
    - '#ffffff'
    - '#ffffff'
  lightness: 1
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
name: Cube Photo
favicon: null
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.38731
layout_spectrum: 0.5361702
