name: Cube Photo
favicon: null
layout_spectrum: 0.94783
typography_spectrum: 0.38731
title: Photo Agency for the Design Press
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fefefe'
    - '#3f3328'
    - '#fed282'
    - '#a6844b'
    - '#b4b8b9'
  brandStrength: 0.1875
  lightness: 1
  saturation: 0.25
  rhythmicContrast: 0.5
purpose: []
